spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/habitos
spring.datasource.username=postgres
spring.datasource.password=root
api.security.token.secret=${JWT_SECRET:my-secret-key}